### ISSUE TITLE
Update runtime to 18.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.bzflag.BZFlag#3]
https://github.com/flathub/flathub/issues/667

**Comment by allejo** [comment]
Resources for both future me and any other BZFlag devs stumbling here

- https://blogs.gnome.org/alexl/2018/08/10/the-birth-of-a-new-runtime/
- https://lists.freedesktop.org/archives/flatpak/2018-August/001233.html
- https://gitlab.com/freedesktop-sdk/freedesktop-sdk/blob/18.08/README.md
