### ISSUE TITLE
Update runtime to 19.08

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.bzflag.BZFlag#6]

**Comment by eszlari** [comment]
@blast007 Your PR (https://github.com/flathub/org.bzflag.BZFlag/pull/7) failed, but you can fix it by updating https://github.com/flathub/shared-modules!

Just run
```
git submodule update --remote --merge
```
and  rename `glu-9.0.0.json` to `glu-9.json`.

**Comment by allejo** [comment]
Closed by #8
